vm_name="ErezsTestAdoAgentVm"
log_analytics_workspace_name="ErezsTestAksWorkspace"
log_analytics_resource_group_name="ErezsTestRG"
virtual_network_resource_group_name="ErezsTestRG"
virtual_network_name="ErezsTestAksVNet"
subnet_name="VmSubnet"